// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockProject1.Models;

#nullable disable

namespace MockProject1.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MockProject1.Models.Course", b =>
                {
                    b.Property<string>("CourseName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CourseName");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MockProject1.Models.Hobby", b =>
                {
                    b.Property<string>("HobbyName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("HobbyName");

                    b.ToTable("Hobbys");
                });

            modelBuilder.Entity("MockProject1.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HobbiesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentID");

                    b.HasIndex("CourseName");

                    b.HasIndex("HobbiesName");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MockProject1.Models.Student", b =>
                {
                    b.HasOne("MockProject1.Models.Course", "Courses")
                        .WithMany("students")
                        .HasForeignKey("CourseName");

                    b.HasOne("MockProject1.Models.Hobby", "Hobbie")
                        .WithMany("studs")
                        .HasForeignKey("HobbiesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Hobbie");
                });

            modelBuilder.Entity("MockProject1.Models.Course", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("MockProject1.Models.Hobby", b =>
                {
                    b.Navigation("studs");
                });
#pragma warning restore 612, 618
        }
    }
}
